# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '槽函数.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
bo=5.893e-6
m=float(input("请输入m:"))
n=float(input("请输入n:"))
dm=float(input("请输入dm:"))
dn=float(input("请输入dn:"))
r=(dm**2-dn**2)/4*(m-n)*bo
print(r)